FROM python:3.12-slim

WORKDIR /app

COPY services/camera/requirements.txt ./

RUN pip install -r requirements.txt

COPY services/camera/ ./
COPY data/images ./data/images/

CMD [ "python", "-u", "main.py" ]
